# Generated by Django 3.0.7 on 2020-06-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_moderation_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='name2',
        ),
    ]
